### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by JLiLab** [milescsmith/ReductionWrappers#3]
Thank you for sharing the script. 

I ran in some errors when using PAGA function. Here is the output (cdS is a Seurat (3.0) object: 
cdS <- PAGA(cdS)
[1] "pca"
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[1] "tsne"
[1] "umap"
Error in alpha$uns$paga$connectivities$todense() %>% `rownames<-`(levels(alpha$obs[[alpha$uns$paga$groups]])) %>%  : 
  could not find function "%>%"

Any suggestions?
Thank you, 
J

**Comment by milescsmith** [comment]
Hi, sorry about how long it has taken to get to this but I had to step away from all things scRNA-seq for a while.

The bug indicated by that last line was due to {magrittr} not being included in the `PAGA()` Roxygen header, which I've now fixed.  The "ValueError" lines were, I believe, due to a change made in pandas, and I've since fixed in [s2a](https://github.com/milescsmith/s2a@0.1.3)

Please let me know if you are still having problems with the function.
